apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s  # frequência de coleta (curta para ver rápido no Grafana)
    scrape_configs:
      - job_name: 'monitor'
        metrics_path: /metrics        # caminho onde seu backend expõe métricas
        static_configs:
          - targets: ['monitor-service:3000']  # DNS do Service dentro do cluster